apiVersion: virtualservers.k8s.nginx.org
kind: VirtualServer
metadata:
  name: nginx-test
spec:
  host: ${FQDN}
  ingressClassName: nginx
  upstreams:
  - name: mars
    service: mars-svc
    port: 80
  - name: jupiter
    service: jupiter-svc
    port: 80
  - name: planet
    service: planet-svc
    port: 80
  routes:
  - path: /mars
    action:
      pass: mars
  - path: /jupiter
    action:
      pass: jupiter
  - path: /
    action:
      pass: planet;